PARAMS:
    bids_root: C:\Users\ianzy\Documents\Research\sleep-benchmark\Michigan_Epilepsy_Data\BIDS
    bids_path_list:
        - subject: umich0020
          session: ieeg01
          datatype: ieeg
          task: all
          run: "01"
          suffix: ieeg
          extension: .lay
          staging_methods: # list of staging methods to use, e.g. ['yasa', 'ad_scalp', 'ad_ieeg', 'ad_all']
            - yasa
            - ad_scalp
            - ad_ieeg
            - ad_all
          stage_full_recording: False # disregards window_start and window_stop if True
          window_start: 10800 # seconds from start of recording
          window_stop: 14400 # seconds from start of recording
          save_figures: True
        - subject: umich0020
          session: ieeg01
          datatype: ieeg
          task: all
          run: "01"
          suffix: ieeg
          extension: .lay
          staging_methods:
            - yasa
            - ad_scalp
            - ad_ieeg
            - ad_all
          stage_full_recording: False
          window_start: 18000
          window_stop: 21600
          save_figures: True
