# for 02-alpha_delta_roc.py
PARAMS:
    bids_root: C:\Users\ianzy\Documents\Research\sleep-benchmark\Michigan_Epilepsy_Data\BIDS
    ### Parameters for each BIDS path:
    # subject: Subject ID
    # session: Session
    # datatype: Data type (e.g., ieeg)
    # task: Task
    # run: Run number
    # suffix: Suffix for the data files
    # extension: File extension
    # stage_full_recording: If True, stage the full recording; if False, use window_start and window_stop
    # window_start: Start time in seconds for staging (if stage_full_recording is False)
    # window_stop: Stop time in seconds for staging (if stage_full_recording is False)
    bids_path_list:
        - subject: umich0020
          session: ieeg01
          datatype: ieeg
          task: all
          run: "01"
          suffix: ieeg
          extension: .lay
          stage_full_recording: False
          window_start: 0
          window_stop: 7200
        - subject: umich0021
          session: ieeg01
          datatype: ieeg
          task: all
          run: "01"
          suffix: ieeg
          extension: .lay
          stage_full_recording: False
          window_start: 0
          window_stop: 7200
        - subject: umich0022
          session: ieeg01
          datatype: ieeg
          task: all
          run: "01"
          suffix: ieeg
          extension: .lay
          stage_full_recording: False
          window_start: 0
          window_stop: 7200
        - subject: umich0023
          session: ieeg01
          datatype: ieeg
          task: all
          run: "01"
          suffix: ieeg
          extension: .lay
          stage_full_recording: False
          window_start: 0
          window_stop: 7200
        - subject: umich0024
          session: ieeg01
          datatype: ieeg
          task: all
          run: "01"
          suffix: ieeg
          extension: .lay
          stage_full_recording: False
          window_start: 0
          window_stop: 7200
